name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier
        run: bun run prettier --check .

      - name: Run TypeScript compiler
        run: bun run tsc --noEmit

      - name: Run tests
        run: bun test
